In [2]:
import pandas as pd
import sklearn
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('ggplot')
from sklearn.model_selection import train_test_split

In [5]:
intents = pd.read_excel('/Users/apple/Desktop/Intent_classification_filtered_1.xlsx')

type(intents)

pandas.core.frame.DataFrame

In [88]:
Intent = pd.DataFrame()
Content = pd.DataFrame()
Intent = intents['Intents']
Content = intents.drop('Intents',axis=1)
type(Intent)

pandas.core.series.Series

In [89]:
print(Content.head)

<bound method NDFrame.head of                                                 Models  Label  \
0                                     P1-Ant2Maven.atl      1   
1                                     P1-Maven2XML.atl      2   
2                                      P46-Ant2XML.atl      2   
3                                       P1-XML2Ant.atl      0   
4                                      P59-XML2XML.atl      6   
..                                                 ...    ...   
169                          P51-Table2SVGBarChart.atl      3   
170                          P51-Table2SVGPieChart.atl      3   
171                          P51-Table2TabularHTML.atl      3   
172                                 P53-METAH2ACME.atl      6   
173  P54-SpreadsheetMLSimplified2SoftwareQualityCon...      1   

                                               Content  \
0    module Ant2Maven;\n\n\n\ncreate OUTMaven : Mav...   
1    module Maven2XML;\n\n\n\ncreate  XML1 : XMLMav...   
2    module Ant

In [90]:
from sklearn.feature_extraction.text import TfidfVectorizer
vect = TfidfVectorizer()
val = vect.fit_transform(Content.tokenized_words)
val.shape

(174, 2508)

In [91]:
from sklearn.feature_extraction.text import TfidfVectorizer
vect = TfidfVectorizer()
val = vect.fit_transform(Intent)
val.shape

(174, 14)

In [92]:
from sklearn.feature_extraction.text import HashingVectorizer
vectorizer = HashingVectorizer(stop_words='english')
X_train = vectorizer.fit_transform(Content.tokenized_words)
#print(X_train)
X_train.shape

(174, 1048576)

In [93]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer(stop_words='english',ngram_range=(2, 2))
X_train_counts = count_vect.fit_transform(Content.tokenized_words)

X_train_counts.shape

(174, 22958)

In [94]:
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
text_clf = Pipeline([('tfidf', TfidfVectorizer()),('clf', KNeighborsClassifier()),])
cv_results = cross_val_score(text_clf, Content.tokenized_words, Intent, cv=3)
print(cv_results)
np.mean(cv_results)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)
[0.47540984 0.53448276 0.27272727]


0.42753995580451204

In [95]:
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
text_clf = Pipeline([('vect', CountVectorizer(ngram_range=(2, 2))),('clf', KNeighborsClassifier()),])
cv_results = cross_val_score(text_clf, Content.tokenized_words, Intent, cv=3)
print(cv_results)
np.mean(cv_results)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)
[0.3442623  0.4137931  0.29090909]


0.3496548298131113

In [96]:
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
text_clf = Pipeline([('hashvector',HashingVectorizer()),('clf', KNeighborsClassifier()),])
cv_results = cross_val_score(text_clf, Content.Content, Intent, cv=3)
print(cv_results)
np.mean(cv_results)


/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)
[0.49180328 0.55172414 0.30909091]


0.4508727752368227

In [97]:
from sklearn.linear_model import SGDClassifier
text_clf_svm = Pipeline([('hashvector',HashingVectorizer()),('clf-svm', SGDClassifier(loss='hinge', penalty='l2',alpha=1e-3, max_iter=1000, random_state=42)),])
cv_results = cross_val_score(text_clf_svm, Content.Content, Intent, cv=3)
print(cv_results)
np.mean(cv_results)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)
[0.47540984 0.5862069  0.34545455]


0.4690237593572811